server
{
    # Listen on port 443 with SSL
    listen 443 ssl;
    listen [::]:443 ssl;

    # Server name for the server block
    server_name amdemuyn.42.fr;

    # SSL certificate and key paths
    ssl_certificate /etc/ssl/certs/nginx.crt;			# certificate
    ssl_certificate_key /etc/ssl/private/nginx.key;		# private key
    ssl_protocols TLSv1.2 TLSv1.3;						# we are using TLS
    ssl_prefer_server_ciphers off;						# we are not using cipher (ciphers are used to encrypt data)

    # Index files for the server
    index index.php index.html index.htm;

    # Root directory for your server
    root /var/www/html/wordpress;

    # Handle requests and redirect to index.php if files are not found
    location /{
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Handle PHP requests
    location ~ \.php$
	{
        try_files $uri = 404;							# try to find the file, if not found return 404
        fastcgi_split_path_info ^(.+\.php)(/.+)$;		# split the path info (this means that the path info is the part of the URL that comes after the script name)
        fastcgi_pass wordpress:9000;					# pass the request to the FastCGI server (wordpress is the name of the FastCGI server)
        fastcgi_index index.php;						# set the index file

        # Standard FastCGI parameters (these are the parameters that are passed to the FastCGI server)
        include fastcgi_params;

        # Pass the script filename to FastCGI server (this is the path to the script that will be executed)
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Pass additional path information to FastCGI server (this is the path info that was split before)
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
