server
{   
    # listen on port 443 with ssl (HTTPS)
    listen 443 ssl;
    listen [::]:443 ssl;

    #config of ssl protocols
    ssl_protocols TLSv1.2 TLSv1.3;

    # config of ssl certificate & privatekey
    ssl_certificate /etc/ssl/certs/my_nginx.crt;
    ssl_certificate_key /etc/ssl/private/my_nginx.key;

    # config of ssl ciphers in off → client chooses cipher (ciphers are used to encrypt data between the server and the client)
    ssl_prefer_server_ciphers off;

    # server_name localhost;
    server_name amdemuyn.42.fr;

    # location of the root directory of the website
    root /var/www/html/wordpress;

    # index file to serve when a directory is requested
    index index.php index.html;

    # location block for handling requests to the root of the website
    # is_args and $args are used to pass query parameters to the index.php file
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # location block for handling PHP files
    location ~ \.php$ {
        try_files $uri = 404;                       # check if the requested PHP file exists, if not return a 404 error
        fastcgi_split_path_info ^(.+\.php)(/.+)$;   # split the URI into 2 parts: script filename and path info (if any)
        fastcgi_pass wordpress:9000;                # pass the request to the FastCGI server (PHP-FPM) running on the "wordpress" service at port 9000
        fastcgi_index index.php;                    # specify the default index file for FastCGI requests

        include fastcgi_params;                     # include the default FastCGI parameters provided by Nginx

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;   # set the SCRIPT_FILENAME parameter to the full path of the requested PHP file
        fastcgi_param PATH_INFO $fastcgi_path_info;                         # set the PATH_INFO parameter to the path info extracted from the URI (if any)    
        fastcgi_param QUERY_STRING $query_string;                           # set the QUERY_STRING parameter to the query string from the original request (if any)
    }
    
    # location block for denying access to hidden files (.env, .git, etc.)
    location ~ /\. {
        deny all;
    }
}