networks:                                 # Define a custom network for the services to communicate
  inception_network:                      # Name of the custom network
    driver: bridge                        # Use the default bridge driver for the network

services:                                 # Define the services that will be run in the containers
  nginx:                                  # Define the nginx service
    container_name: nginx                 # Name of the nginx container
    build: ./requirements/nginx           # Build the nginx image from the Dockerfile in the specified directory
    ports:                                # Map port 443 on the host to port 443 in the container for HTTPS 
      - "443:443"
    volumes:                              # Mount the wordpress volume to the nginx container to serve the WordPress files
      - wordpress:/var/www/html/wordpress
    depends_on:                           # Ensure that the nginx service starts after the wordpress service
      - wordpress
    networks:                             # Connect the nginx service to the custom network
      - inception_network
    restart: always                       # Always restart the nginx container if it stops or crashes

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    expose:
      - "9000"
    restart: always

volumes:                                  # Define named volumes for persistent data storage
  mariadb:
  wordpress:

##FOR LINUX
#volumes:
#  mariadb:
#    name: mariadb
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/login/data/mariadb

#  wordpress:
#    name: wordpress
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/login/data/wordpress