; This configuration file defines a process pool for PHP-FPM named 'www'.
; This configuration is tailored for low-resource servers.
; It limits the number of PHP-FPM child processes to 5 to prevent CPU and memory overload. 
; The dynamic process management mode allows for automatic adjustments based on demand, ensuring efficiency. 
; Controlled parameters for starting and spare servers maintain stability without excessive resource usage. 
; Running processes as the `www-data` user enhances security by minimizing privileges, reducing the risk of vulnerabilities affecting server performance.



; Start a new pool named 'www'.
; The variable $pool can be used in any directive and will be replaced by the pool name ('www' here)
[www]

; User and group for the processes of this pool
user = www-data
group = www-data

; The address on which the server will listen to requests.
listen = 0.0.0.0:9000

; The number of child processes is adjusted dynamically based on the following directives:
; pm.max_children, pm.start_servers, pm.min_spare_servers, pm.max_spare_servers
pm = dynamic

; Maximum number of child processes that can be launched at the same time.
; It should always be greater than pm.start_servers.
pm.max_children = 5

; Number of processes to start when the pool is initialized.
; If this number is set to 0, no child processes will be started.
pm.start_servers = 2

; Minimum desired amount of server child processes.
; If the number of child processes falls below this number, new processes will be spawned.
pm.min_spare_servers = 1

; Maximum desired amount of server child processes.
; If the number of child processes exceeds this number, excess processes will be killed.
pm.max_spare_servers = 3
